# Generated by Django 5.2.6 on 2025-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Add country"),
        ),
    ]
