# Generated by Django 5.2.6 on 2025-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(max_length=150, verbose_name="Add country"),
        ),
    ]
