# Generated by Django 5.2.6 on 2025-10-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True, default="img/no_image.png", null=True, upload_to="blog_previews/", verbose_name="Превью"
            ),
        ),
    ]
