# Generated by Django 5.2.6 on 2025-10-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Введите описание породы", null=True, verbose_name="Описание"
            ),
        ),
    ]
