# Generated by Django 5.2.6 on 2025-10-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Введите описание категории", null=True, verbose_name="Описание"
            ),
        ),
    ]
