# Generated by Django 5.2.6 on 2025-10-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_image_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="img/no_image.png", null=True, upload_to="products/", verbose_name="Изображение"
            ),
        ),
    ]
